services:

  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MOTD: "ยง3mjanglin.com"
      TYPE: "PAPER"
      MEMORY: "4G"
    stdin_open: true
    tty: true
    volumes:
      - ./server:/data
    restart: on-failure:3
    ports:
      - "25565:25565"


  # WEB SERVER
  ########################################
  # node:
  #   image: "node:latest"
  #   user: "node"
  #   working_dir: /node/app
  #   volumes:
  #     - ./web:/node/app
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - "8888:8888"
  #   command: "npm run dev"
